USE [SQL_ASM2]
GO
	INSERT INTO [dbo].[NguoiDung]([ID],[Ten],[DiaChi],[SDT]) VALUES('SV01','Nguyen Van A','HaNoi','12345')
	INSERT INTO [dbo].[NguoiDung]([ID],[Ten],[DiaChi],[SDT]) VALUES('SV03','Nguyen Van B','HCM','23454')
	INSERT INTO [dbo].[NguoiDung]([ID],[Ten],[DiaChi],[SDT]) VALUES('SV02','Nguyen Van C','DaNang','21432')
	INSERT INTO [dbo].[NguoiDung]([ID],[Ten],[DiaChi],[SDT]) VALUES('GV01','Nguyen Van D','HaNoi','67543')
	INSERT INTO [dbo].[NguoiDung]([ID],[Ten],[DiaChi],[SDT]) VALUES('GV03','Nguyen Van E','HCM','34521')
	INSERT INTO [dbo].[NguoiDung]([ID],[Ten],[DiaChi],[SDT]) VALUES('GV02','Nguyen Van F','DaNang','98605')
	-----
	INSERT INTO [dbo].[BaiViet]([MaBai],[DungLuong],[ID]) VALUES('BV01','100','SV02')
	INSERT INTO [dbo].[BaiViet]([MaBai],[DungLuong],[ID]) VALUES('BV07','150','SV02')
	INSERT INTO [dbo].[BaiViet]([MaBai],[DungLuong],[ID]) VALUES('BV03','200','GV02')
	INSERT INTO [dbo].[BaiViet]([MaBai],[DungLuong],[ID]) VALUES('BV04','400','GV03')
	INSERT INTO [dbo].[BaiViet]([MaBai],[DungLuong],[ID]) VALUES('BV02','300','SV01')
	INSERT INTO [dbo].[BaiViet]([MaBai],[DungLuong],[ID]) VALUES('BV05','600','SV03')
	INSERT INTO [dbo].[BaiViet]([MaBai],[DungLuong],[ID]) VALUES('BV06','700','GV01')
	----
	INSERT INTO [dbo].[Comment]([MaCmt],[ID],[MaBai],[ND]) VALUES('CMT01','SV02','BV04','AAAAAAAAA')
	INSERT INTO [dbo].[Comment]([MaCmt],[ID],[MaBai],[ND]) VALUES('CMT04','GV01','BV01','BBBBBBBB')
	INSERT INTO [dbo].[Comment]([MaCmt],[ID],[MaBai],[ND]) VALUES('CMT03','SV01','BV06','NNNNNNNN')
	INSERT INTO [dbo].[Comment]([MaCmt],[ID],[MaBai],[ND]) VALUES('CMT02','GV03','BV02','FFFFFFFF')
	INSERT INTO [dbo].[Comment]([MaCmt],[ID],[MaBai],[ND]) VALUES('CMT05','SV03','BV05','DDDDDDDD')
	INSERT INTO [dbo].[Comment]([MaCmt],[ID],[MaBai],[ND]) VALUES('CMT06','GV02','BV03','DDDDDDDD')
	-----
	INSERT INTO [dbo].[Share]([ID],[MaBai],[Nguoi_Share]) VALUES('SV01','BV01','Nguyen Van A')
	INSERT INTO [dbo].[Share]([ID],[MaBai],[Nguoi_Share]) VALUES('SV03','BV04','Nguyen Van C')
	INSERT INTO [dbo].[Share]([ID],[MaBai],[Nguoi_Share]) VALUES('GV02','BV06','Nguyen Van F')
	INSERT INTO [dbo].[Share]([ID],[MaBai],[Nguoi_Share]) VALUES('SV02','BV04','Nguyen Van B')
	INSERT INTO [dbo].[Share]([ID],[MaBai],[Nguoi_Share]) VALUES('GV01','BV02','Nguyen Van D')
	INSERT INTO [dbo].[Share]([ID],[MaBai],[Nguoi_Share]) VALUES('GV03','BV05','Nguyen Van E')
	----
	INSERT INTO [dbo].[Like_Cmt]([ID],[NguoiLike],[MaCmt]) VALUES('SV02','Nguyen Van B','CMT06')
	INSERT INTO [dbo].[Like_Cmt]([ID],[NguoiLike],[MaCmt]) VALUES('GV02','Nguyen Van F','CMT06')
	INSERT INTO [dbo].[Like_Cmt]([ID],[NguoiLike],[MaCmt]) VALUES('SV01','Nguyen Van A','CMT01')
	INSERT INTO [dbo].[Like_Cmt]([ID],[NguoiLike],[MaCmt]) VALUES('GV03','Nguyen Van E','CMT06')
	INSERT INTO [dbo].[Like_Cmt]([ID],[NguoiLike],[MaCmt]) VALUES('SV03','Nguyen Van C','CMT02')
	INSERT INTO [dbo].[Like_Cmt]([ID],[NguoiLike],[MaCmt]) VALUES('GV01','Nguyen Van D','CMT03')
	--------
	INSERT INTO [dbo].[Like_Bv]([ID],[MaBai],[NguoiLike]) VALUES('SV02','BV02','Nguyen Van B')
	INSERT INTO [dbo].[Like_Bv]([ID],[MaBai],[NguoiLike]) VALUES('GV02','BV03','Nguyen Van F')
	INSERT INTO [dbo].[Like_Bv]([ID],[MaBai],[NguoiLike]) VALUES('SV01','BV02','Nguyen Van A')
	INSERT INTO [dbo].[Like_Bv]([ID],[MaBai],[NguoiLike]) VALUES('GV03','BV05','Nguyen Van E')
	INSERT INTO [dbo].[Like_Bv]([ID],[MaBai],[NguoiLike]) VALUES('SV03','BV01','Nguyen Van C')
	INSERT INTO [dbo].[Like_Bv]([ID],[MaBai],[NguoiLike]) VALUES('GV01','BV04','Nguyen Van D')
	--------
    INSERT INTO [dbo].[Post]([ID],[MaBai]) VALUES('SV02','BV01')
	INSERT INTO [dbo].[Post]([ID],[MaBai]) VALUES('GV02','BV03')
	INSERT INTO [dbo].[Post]([ID],[MaBai]) VALUES('GV03','BV04')
	INSERT INTO [dbo].[Post]([ID],[MaBai]) VALUES('SV01','BV02')
	INSERT INTO [dbo].[Post]([ID],[MaBai]) VALUES('SV03','BV05')
	INSERT INTO [dbo].[Post]([ID],[MaBai]) VALUES('GV01','BV06')
	--------
	INSERT INTO [dbo].[File_DL]([MaFile],[MaBai],[ChuyenNganh],[TenFile]) VALUES('F01','BV01','TOAN','File Toan')
	INSERT INTO [dbo].[File_DL]([MaFile],[MaBai],[ChuyenNganh],[TenFile]) VALUES('F06','BV06','LY','File ly')
	INSERT INTO [dbo].[File_DL]([MaFile],[MaBai],[ChuyenNganh],[TenFile]) VALUES('F04','BV04','HOA','File hoa')
	INSERT INTO [dbo].[File_DL]([MaFile],[MaBai],[ChuyenNganh],[TenFile]) VALUES('F03','BV03','SINH','File sinh')
	INSERT INTO [dbo].[File_DL]([MaFile],[MaBai],[ChuyenNganh],[TenFile]) VALUES('F05','BV05','ANH','File anh')
	INSERT INTO [dbo].[File_DL]([MaFile],[MaBai],[ChuyenNganh],[TenFile]) VALUES('F02','BV02','VAN','File van')
GO